# Generated by Django 2.1.3 on 2018-11-06 15:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181104_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('followers', models.ManyToManyField(to='news.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Source'),
        ),
    ]
