# Generated by Django 2.1.3 on 2018-11-10 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181110_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 17, 25, 12, 623532)),
            preserve_default=False,
        ),
    ]
