# Generated by Django 2.1.3 on 2018-11-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_share_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='api.UserProfile'),
        ),
    ]
