# Generated by Django 2.1.3 on 2019-01-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190102_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='api.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_items',
            field=models.ManyToManyField(blank=True, to='api.Media'),
        ),
    ]
