# Generated by Django 2.1.3 on 2019-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190103_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='followers',
            field=models.ManyToManyField(blank=True, to='api.UserProfile'),
        ),
    ]
