# Generated by Django 2.2.8 on 2020-02-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190106_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('order',)},
        ),
    ]
