# Generated by Django 2.2.10 on 2020-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter',
            field=models.CharField(default='2347234', max_length=100),
        ),
    ]
