# Generated by Django 2.2.10 on 2020-03-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200305_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
