name: Django application

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Django Test
      env:
        SECRET_KEY: thisisasecret
        CLOUDINARY_CLOUD_NAME: mycloudname
      run: |
        pipenv run coverage run --source='.' manage.py test
    - name: Collect test coverage
      run: |
        pipenv run coverage report
        pipenv run codecov --token=0073250f-9ea0-4d00-9012-c084970ac0ae